run_config:
  condition:
    name: palaestrai.experiment:VanillaRunGovernorTerminationCondition
    params: {}
schedule:
- training:
    agents:
    - actuators: [midas_powergrid.Powergrid-0.0-load-0-1.p_mw, midas_powergrid.Powergrid-0.0-load-0-1.q_mvar,
        midas_powergrid.Powergrid-0.0-load-1-3.p_mw, midas_powergrid.Powergrid-0.0-load-1-3.q_mvar,
        midas_powergrid.Powergrid-0.0-load-10-12.p_mw, midas_powergrid.Powergrid-0.0-load-10-12.q_mvar,
        midas_powergrid.Powergrid-0.0-load-11-13.p_mw, midas_powergrid.Powergrid-0.0-load-11-13.q_mvar,
        midas_powergrid.Powergrid-0.0-load-12-14.p_mw, midas_powergrid.Powergrid-0.0-load-12-14.q_mvar,
        midas_powergrid.Powergrid-0.0-load-2-4.p_mw, midas_powergrid.Powergrid-0.0-load-2-4.q_mvar,
        midas_powergrid.Powergrid-0.0-load-3-5.p_mw, midas_powergrid.Powergrid-0.0-load-3-5.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-0-1.p_mw, midas_powergrid.Powergrid-0.0-sgen-0-1.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-1-3.p_mw, midas_powergrid.Powergrid-0.0-sgen-1-3.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-10-12.p_mw, midas_powergrid.Powergrid-0.0-sgen-10-12.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-11-13.p_mw, midas_powergrid.Powergrid-0.0-sgen-11-13.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-12-14.p_mw, midas_powergrid.Powergrid-0.0-sgen-12-14.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-2-4.p_mw, midas_powergrid.Powergrid-0.0-sgen-2-4.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-3-5.p_mw, midas_powergrid.Powergrid-0.0-sgen-3-5.q_mvar]
      brain:
        name: harl:SACBrain
        params:
          batch_size: 1024
          fc_dims: [8, 8]
          gamma: 0.98
          lr: 0.0003
          replay_size: 3000000
          update_after: 1000
          update_every: 10
      muscle:
        name: harl:SACMuscle
        params: {start_steps: 100}
      name: gandalf
      objective:
        name: midas.tools.palaestrai:ArlDefenderObjective
        params: {}
      sensors: &id001 [midas_powergrid.Powergrid-0.0-bus-1.vm_pu, midas_powergrid.Powergrid-0.0-bus-1.va_degree,
        midas_powergrid.Powergrid-0.0-bus-10.vm_pu, midas_powergrid.Powergrid-0.0-bus-10.va_degree,
        midas_powergrid.Powergrid-0.0-bus-11.vm_pu, midas_powergrid.Powergrid-0.0-bus-11.va_degree,
        midas_powergrid.Powergrid-0.0-bus-12.vm_pu, midas_powergrid.Powergrid-0.0-bus-12.va_degree,
        midas_powergrid.Powergrid-0.0-bus-13.vm_pu, midas_powergrid.Powergrid-0.0-bus-13.va_degree,
        midas_powergrid.Powergrid-0.0-bus-14.vm_pu, midas_powergrid.Powergrid-0.0-bus-14.va_degree,
        midas_powergrid.Powergrid-0.0-bus-2.vm_pu, midas_powergrid.Powergrid-0.0-bus-2.va_degree,
        midas_powergrid.Powergrid-0.0-bus-3.vm_pu, midas_powergrid.Powergrid-0.0-bus-3.va_degree,
        midas_powergrid.Powergrid-0.0-bus-4.vm_pu, midas_powergrid.Powergrid-0.0-bus-4.va_degree,
        midas_powergrid.Powergrid-0.0-bus-5.vm_pu, midas_powergrid.Powergrid-0.0-bus-5.va_degree,
        midas_powergrid.Powergrid-0.0-bus-6.vm_pu, midas_powergrid.Powergrid-0.0-bus-6.va_degree,
        midas_powergrid.Powergrid-0.0-bus-7.vm_pu, midas_powergrid.Powergrid-0.0-bus-7.va_degree,
        midas_powergrid.Powergrid-0.0-bus-8.vm_pu, midas_powergrid.Powergrid-0.0-bus-8.va_degree,
        midas_powergrid.Powergrid-0.0-bus-9.vm_pu, midas_powergrid.Powergrid-0.0-bus-9.va_degree,
        midas_powergrid.Powergrid-0.0-line-0.loading_percent, midas_powergrid.Powergrid-0.0-line-0.in_service,
        midas_powergrid.Powergrid-0.0-line-1.loading_percent, midas_powergrid.Powergrid-0.0-line-1.in_service,
        midas_powergrid.Powergrid-0.0-line-10.loading_percent, midas_powergrid.Powergrid-0.0-line-10.in_service,
        midas_powergrid.Powergrid-0.0-line-11.loading_percent, midas_powergrid.Powergrid-0.0-line-11.in_service,
        midas_powergrid.Powergrid-0.0-line-12.loading_percent, midas_powergrid.Powergrid-0.0-line-12.in_service,
        midas_powergrid.Powergrid-0.0-line-13.loading_percent, midas_powergrid.Powergrid-0.0-line-13.in_service,
        midas_powergrid.Powergrid-0.0-line-14.loading_percent, midas_powergrid.Powergrid-0.0-line-14.in_service,
        midas_powergrid.Powergrid-0.0-line-2.loading_percent, midas_powergrid.Powergrid-0.0-line-2.in_service,
        midas_powergrid.Powergrid-0.0-line-3.loading_percent, midas_powergrid.Powergrid-0.0-line-3.in_service,
        midas_powergrid.Powergrid-0.0-line-4.loading_percent, midas_powergrid.Powergrid-0.0-line-4.in_service,
        midas_powergrid.Powergrid-0.0-line-5.loading_percent, midas_powergrid.Powergrid-0.0-line-5.in_service,
        midas_powergrid.Powergrid-0.0-line-6.loading_percent, midas_powergrid.Powergrid-0.0-line-6.in_service,
        midas_powergrid.Powergrid-0.0-line-7.loading_percent, midas_powergrid.Powergrid-0.0-line-7.in_service,
        midas_powergrid.Powergrid-0.0-line-8.loading_percent, midas_powergrid.Powergrid-0.0-line-8.in_service,
        midas_powergrid.Powergrid-0.0-line-9.loading_percent, midas_powergrid.Powergrid-0.0-line-9.in_service]
    - actuators: [midas_powergrid.Powergrid-0.0-load-4-6.p_mw, midas_powergrid.Powergrid-0.0-load-4-6.q_mvar,
        midas_powergrid.Powergrid-0.0-load-5-7.p_mw, midas_powergrid.Powergrid-0.0-load-5-7.q_mvar,
        midas_powergrid.Powergrid-0.0-load-6-8.p_mw, midas_powergrid.Powergrid-0.0-load-6-8.q_mvar,
        midas_powergrid.Powergrid-0.0-load-7-9.p_mw, midas_powergrid.Powergrid-0.0-load-7-9.q_mvar,
        midas_powergrid.Powergrid-0.0-load-8-10.p_mw, midas_powergrid.Powergrid-0.0-load-8-10.q_mvar,
        midas_powergrid.Powergrid-0.0-load-9-11.p_mw, midas_powergrid.Powergrid-0.0-load-9-11.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-4-6.p_mw, midas_powergrid.Powergrid-0.0-sgen-4-6.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-5-7.p_mw, midas_powergrid.Powergrid-0.0-sgen-5-7.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-6-8.p_mw, midas_powergrid.Powergrid-0.0-sgen-6-8.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-7-9.p_mw, midas_powergrid.Powergrid-0.0-sgen-7-9.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-8-10.p_mw, midas_powergrid.Powergrid-0.0-sgen-8-10.q_mvar,
        midas_powergrid.Powergrid-0.0-sgen-9-11.p_mw, midas_powergrid.Powergrid-0.0-sgen-9-11.q_mvar]
      brain:
        name: harl:SACBrain
        params:
          batch_size: 1024
          fc_dims: [8, 8]
          gamma: 0.98
          lr: 0.0003
          replay_size: 1000000
          update_after: 1000
          update_every: 10
      muscle:
        name: harl:SACMuscle
        params: {start_steps: 100}
      name: sauron
      objective:
        name: midas.tools.palaestrai:ArlAttackerObjective
        params: {}
      sensors: *id001
    environments:
    - environment:
        name: palaestrai_mosaik:MosaikEnvironment
        params:
          arl_sync_freq: 60
          description_func: describe
          end: 24*60*60*15
          instance_func: get_world
          module: midas.tools.palaestrai:Descriptor
          params:
            config: run_files/08dced86-324c-11ef-bc8c-8e4c9fde469b/individual_24_scenario.yml
            end: 24*60*60* 15
            mosaik_params:
              addr: [127.0.0.1, 0]
            name: carl_cigre_ts
            silent: true
            start_date: random
            step_size: 60
            store_params: {buffer_size: 1000, filename: 08dced86-324c-11ef-bc8c-8e4c9fde469b_individual_24,
              keep_old_files: true}
          silence_missing_input_connections_warning: true
        uid: midas_powergrid
      reward:
        name: midas.tools.palaestrai.rewards:ExtendedGridHealthReward
        params: {}
    phase_config: {episodes: 12, mode: train, worker: 1}
    simulation:
      conditions:
      - name: palaestrai.simulation:VanillaSimControllerTerminationCondition
        params: {}
      name: palaestrai.simulation:TakingTurns
- test:
    phase_config: {episodes: 15, mode: test, worker: 1}
seed: 123
uid: Diss-LHa-resilience-evaluation-with-attacker_individual_24
version: 3.5.0
